name: Lint
on:
  pull_request:
    branches: ["master"]
    paths:
      - "**/*.kt"
      - "**/*.xml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Install ktlint"
        uses: nbadal/action-ktlint-setup@v1
        with:
          ktlint_version: '0.40.0'

      - name: "Run Ktlint"
        run: ./gradlew ktlintCheck

      - name: "Run Android Lint"
        run: ./gradlew lintDebug

      - name: "Upload Ktlint report"
        uses: actions/upload-artifact@v2
