name: Ktlint Check
on:
  pull_request:
    branches: ["master"]
    paths:
      - "**/*.kt"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Install ktlint"
        uses: nbadal/action-ktlint-setup@v1
        with:
          ktlint_version: '0.40.0'

      - run: ktlint --version
        shell: bash