name: Semantic Release

on:
  push:
    branches:
      - master

jobs:
  semantic-release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1 Checkout Repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      # Step 2 Setup Ruby
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.4.3'

      # Step 3 Install the bundler & Fastlane (Create environment for ruby to avoid dependency hell and manage the dependencies versions)
      - name: Install bundler
        run: |
          gem install bundler:2.2.27
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      # Step 4 Execute Semantic Release
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 17
          extra_plugins: |
            @semantic-release/changelog@5
            @semantic-release/exec@5
            @semantic-release/git@9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: octopus-developers
          GIT_AUTHOR_EMAIL: developers@octopus.com
          GIT_COMMITTER_NAME: octopus-developers
          GIT_COMMITTER_EMAIL: developers@octopus.com
