name: Test

on:
  pull_request:
    branches: ["master", "develop"]
  push:
    branches: ["master", "develop"]

jobs:
  test:
    runs-on: ubuntu-latest

    needs: Build with Gradle

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Test
        run: ./gradlew testDebugUnitTest
